######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:40:01 2011
######################################################################
QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += controlwin.h
SOURCES += controlMain.cpp controlwin.cpp
