######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:42:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += finish.cpp
