######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:41:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += sync.cpp
