######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:49:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += back.cpp
