######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:41:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mylabel.h
SOURCES += main.cpp mylabel.cpp
